/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDrawer: typeof import('./src/components/AppDrawer.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    BaseChart: typeof import('./src/components/charts/BaseChart.vue')['default']
    ConnectionsCntChart: typeof import('./src/components/charts/ConnectionsCntChart.vue')['default']
    EmptyContent: typeof import('./src/components/EmptyContent.vue')['default']
    Error404: typeof import('./src/components/Error404.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GenPlanKeysDialog: typeof import('./src/components/plan/GenPlanKeysDialog.vue')['default']
    GlobalDialog: typeof import('./src/components/global/GlobalDialog.vue')['default']
    GlobalSnackbar: typeof import('./src/components/global/GlobalSnackbar.vue')['default']
    NetworkChart: typeof import('./src/components/charts/NetworkChart.vue')['default']
    Plan: typeof import('./src/components/plan/Plan.vue')['default']
    PlanDialog: typeof import('./src/components/plan/PlanDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrafficChart: typeof import('./src/components/charts/TrafficChart.vue')['default']
    TrafficTrendsBtnGroup: typeof import('./src/components/TrafficTrendsBtnGroup.vue')['default']
  }
}
