name: Release Build
# 仓库写入权限
permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for test build'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install cross compilers
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            gcc-mingw-w64-x86-64 \
            g++-mingw-w64-x86-64

      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            TAG="test"
          else
            VERSION="${GITHUB_REF_NAME}"
            TAG="${GITHUB_REF_NAME}"
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          echo "Version: $VERSION"
          echo "Tag: $TAG"

      - name: Build
        run: |
          chmod +x scripts/build_all.sh
          ./scripts/build_all.sh ${{ steps.version.outputs.version }}
          cp build/linux/* scripts/docker/
          ls scripts/docker/

      - name: Create or Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.version }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
          files: |
            build/linux/*
            build/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./scripts/docker
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clipshare-forward-server:${{ steps.version.outputs.version }}
#            ${{ secrets.DOCKERHUB_USERNAME }}/clipshare-forward-server:latest
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
